name: kreki119
description: Kreki app for 119
publish_to: none
version: 1.0.3+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: '2.8.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.5.1
  flutter_svg: ^1.1.6
  dio: ^4.0.6
  shared_preferences: ^2.0.10
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_vector_icons: 1.0.0
  google_fonts: ^3.0.1
  ringtone_set: ^0.0.3
  cached_network_image: ^3.2.3
  animations: ^2.0.2
  firebase_messaging: ^14.6.9
  logger: ^1.1.0
  # geolocator_apple: ^2.3.2
  pretty_dio_logger: ^1.1.1
  font_awesome_flutter: ^10.3.0
  fluttertoast: ^8.0.8
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  the_apple_sign_in: ^1.1.1
  sign_in_with_apple: ^5.0.0
  package_info: ^2.0.2
  provider: ^6.0.0
  in_app_update: ^4.2.1
  google_sign_in: ^5.0.7
  nb_utils: ^5.0.5
  animated_bottom_navigation_bar: ^1.1.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  firebase_analytics: ^10.1.0
  flutter_local_notifications: ^12.0.2
  firebase_notifications_handler: ^1.1.0
  image_picker: ^0.8.4+11
  permission_handler: ^10.2.0
  audioplayers: ^2.0.0
  webview_flutter: ^4.0.1
  url_launcher: ^6.1.7
  google_maps_flutter: ^2.2.3
  google_maps_flutter_android: ^2.4.0
  snapping_sheet: ^3.1.0
  sliding_up_panel: ^2.0.0+1
  xml: ^6.1.0
  xml2json: ^5.3.6
  weather: ^2.0.1
  firebase_storage: ^11.1.0
  uuid: ^3.0.7
  another_flushbar: ^1.12.30
  device_info_plus: ^8.0.0
  flutter_native_splash: ^2.2.18 #https://pub.dev/packages/flutter_native_splash
  package_info_plus: ^3.0.2
#  app_settings: ^4.2.0 #https://pub.dev/packages/app_settings


dev_dependencies:
  #  flutter_test:
  #    sdk: flutter
  flutter_lints: ^2.0.1
  analyzer: any
  dart_code_metrics: any
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_kreki.png"
  image_path_ios: "assets/images/logo_kreki.png"
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/
    - assets/raw/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/Roboto-Light.ttf
          weight: 200
        - asset: fonts/Roboto-Regular.ttf
          weight: 200
        - asset: fonts/Roboto-Medium.ttf
          weight: 300
        - asset: fonts/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/Roboto-Italic.ttf
          style: italic