// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoou9q7_TiNzTI0yDYdte-moEjF-o5gR8',
    appId: '1:293071833413:android:9e934bb9f0f3d6ac2e162c',
    messagingSenderId: '293071833413',
    projectId: 'devkreki-80095',
    databaseURL: 'https://devkreki-80095-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'devkreki-80095.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDnZk0Ur4CEGgxCeRu-v6GrieTo0QBeGI',
    appId: '1:293071833413:ios:e6328381337c71972e162c',
    messagingSenderId: '293071833413',
    projectId: 'devkreki-80095',
    databaseURL: 'https://devkreki-80095-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'devkreki-80095.appspot.com',
    androidClientId: '293071833413-1cu1vpdi1edte9recost04c2qu1eitv1.apps.googleusercontent.com',
    iosClientId: '293071833413-0pfam6245q7n20ukrogsmq7lcqpatt3n.apps.googleusercontent.com',
    iosBundleId: 'com.rpc.kreki119',
  );
}
